### PR TITLE
Rename 6to5 to Babel

### PR DESCRIPTION
**Pull request by sebmck**
6to5 has been renamed to Babel, more information [here](http://babeljs.io/blog/2015/02/15/not-born-to-die/).

### CODE REVIEW

**Comment by paulcbetts** [comment]
@sebmck 'use 6to5' is not just a find-replace in the README, you need to actually fix the code

**Comment by paulcbetts** [comment]
I'm an idiot, this is great - thanks for doing this!

**Comment by sebmck** [comment]
Hold up, few discrepancies I just spotted.

**Comment by sebmck** [comment]
Fixed.

**Pull request merged**
