### PR TITLE
Add terminal tests

### LINKED ISSUE #6: Set up unit tests

### PR DESCRIPTION
**Pull request by mcolyer**
This is a follow on from #33 and should fix #6.

The current state of things is that `script/run -tr .` runs the full test suite and an exit value of 0 indicates success and 1 indicates failure.

## TODO

* [x] Port the Atom spec runner Grunt task
* [ ] Set up the build system for tests

### CODE REVIEW

**Comment by mcolyer** [comment]
@paulcbetts what were you thinking about the setting up the build system for tests? Did you want to have this running on travis CI?

Atom has https://github.com/atom/ci, but it seems like we would need to periodically produce tarballs which travis could then download.

**Comment by paulcbetts** [comment]
@mcolyer So, these tests are for users to write their own tests, I don't know that we need to run CI on atom-shell-starter itself

**Comment by benogle** [comment]
> I don't know that we need to run CI on atom-shell-starter itself

We probably should for the browser code. There is a lot of code in there, and the browser stuff is hard to test manually. @maxbrunsfeld is working on tests for the browser bits of atom right now.

**Comment by mcolyer** [comment]
Okay so `script/grunt run-specs` now works as expected (the output could use some improvements but I think we should leave that for another PR). We should merge #39 and then this.

**Comment by paulcbetts** [comment]
Thanks guys!

**Pull request merged**
