### PR TITLE
Add in application test suite

### PR DESCRIPTION
**Pull request by mcolyer**
This builds upon @stefanbuck's work, to add a test suite to atom-shell-starter. It now properly runs `spec-bootstrap.coffee` and the next step is to integrate jasmine into that file.

I've also integrated #31 here as it fixes the crashing issues, as well as logging to console which makes debugging substantially easier.

I'll continue to work on this as I have time but if @paulcbetts or @stefanbuck want to jump in that's :cool: too.

## TODO

* [x] Rig up app startup so that we can run tests
* [x] Set up the test framework inside a Renderer context
* [x] Rig a menu item that will run unit tests on-demand
* [x] Pop a Window with Jasmine rigged up which starts executing tests
* [x] Fix the menu items to work with the test window.
* [ ] ~~Port the Atom spec runner Grunt task~~
* [ ] ~~Set up the build system for tests~~

### CODE REVIEW

**Comment by stefanbuck** [comment]
@mcolyer :+1::+1::+1:  I will try to find some time this week to take a closer look.

**Comment by mcolyer** [comment]
So I got a bit further this morning:

screen shot 2015-01-27 at 7 45 51 am

The next step is to actually load in the specs (as well as get the proper stylesheets loaded). I'm also not sure that I love modifying [boot.js](https://github.com/mcolyer/atom-shell-starter/commit/72836038f7d31c207ab56e867f161f44c2081ca0#diff-f2e5dc634d0216b4a80113286190ef15L97), I think we probably should just not require it and do our own setup instead but I wanted to get something working.

**Comment by paulcbetts** [comment]
@mcolyer We had to modify boot.js in our setup :(

**Comment by mcolyer** [comment]
So now I have tests running, need to hook up the terminal runner next.

screen shot 2015-01-28 at 7 22 20 am

**Comment by paulcbetts** [comment]
@mcolyer You're doin' the Lord's work

**Comment by mcolyer** [comment]
So I'm tracking to track down what causes this branch to crash atom-shell after a minute or two of running. It doesn't happen on master but I'm puzzled as to what change here could cause it to crash.

**Comment by mcolyer** [comment]
> So I'm tracking to track down what causes this branch to crash atom-shell after a minute or two of running. It doesn't happen on master but I'm puzzled as to what change here could cause it to crash.

Well that took far long than I wanted, you need to [hold a reference](https://github.com/mcolyer/atom-shell-starter/commit/64280c6f8fef67337f13a87a46e907d1951a19e5) to the windows you create otherwise node will try to GC them and crash the process.

**Comment by mcolyer** [comment]
@paulcbetts so I've removed the WIP here, this is already a pretty complete change and I'd like to get it merged. Any objections?

I'm going to do a follow-on PR for the terminal reporting, just to keep things clean.

**Comment by paulcbetts** [comment]
:+1:

**Comment by mcolyer** [comment]
@paulcbetts I can't merge as I don't have access, can you merge or add me?

**Pull request merged**
